var JOKES = [
    "The saw can Fall and Static, because it got jealous of the platform.",
    "Steel Blocks? Hmm; let me punch them... OW!!!!",
    "FlukeDude Ltd. cannot sue me because they do not have trademarks nor copyrights over this game.",
    //"Switch BLOCKS!? Now we're talking.",
    'Fun Fact: the H in "Walker H" stands for "Helmet"',
    "Are you on the moon in the \"Moon\" theme? \n Because there's another moon in the middle of the Moon theme's background",
    "Fun Fact: FlukeDude Ltd is still the legal name for Fluke Games",
    "Boosters are NOT P2W",
    "The Achievement Pass is NOT a Battle Pass. Please! (Also not Pay-2-Win)",
    "Downward trampolines feel like they should exist; but don't. Maybe that's just me.",
    "Fun Fact: Mini Spikes did not exist until the Super Level Pack was released.",
    "Another Impossible Game? Wow.",
    "The punch powerup removes 2.5 blocks in front of you and 1 1/3 blocks above.",
    "Fun Fact: Speed changes can teleport you forwards given enough velocity.",
    "Too bad this isn't the world's hardest game.",
    "You like impossible quizzes? Too bad; here's a game instead!",
    "Geometry Dash is quite a nice game; try it out!",
    '"The Impossible Game? That can\'t be true."',
    "Player Stacks might despawn. Use with caution.",
    "World 3 is supposed to have triangles in the background. I have no idea why it was removed",
    "World 4 was never shown in any of the trailers.",
    "You can export levels and use them in the original game if you don't use new features.",
    "Always Free!",
    "Always Free!",
    "Always Free!",
    "Fluked Gamers",
    "Puedes cambiar el idioma en el boton de abajo.",
    "Puedes cambiar el idioma en el boton de abajo.",
    "Outline/Alfredo Gamer approved!",
    "Outline/Alfredo Gamer approved!",
    "Outline/Alfredo Gamer approved!",
    "The Impossibler Game",
    "The 3.5 The Impossible Games",
    'The "Dreamy" background is a shader',
    "The + in the title is there for a reason",
    "Feel free to contribute in the github repo!",
    "Fluked Games is not responsible for this amalgamation",
    "Hey, could you do me a favor?",
    "Why didn't World 4 have it's own bottom textures?",
    "Fun Fact: Player Stacks despawn after around 10 vertical blocks",
    "Fun Fact: 2x Falling Platforms are unreliable",
    "Fun Fact: This game is mobile friendly",
    "Fun Fact: I originaly wanted to remake the game. Looks like I have a better way now.",
    "The falling saw is quite the novel concept",
    "Move-On-Switch Platforms and Saws!",
    "Only the variables and functions are obfuscated; object properties are not.",
    
  ],
  currentJoke = Math.random() > 0.5 ? "This is actually the APK version. Have fun!" : "Outline/Alfredo Gamer approved!"//JOKES[Math.floor(Math.random() * JOKES.length)];
