var JOKES = [
    "FlukeDude Ltd. cannot sue me because they do not have trademarks nor copyrights over this game.",
    "Switch BLOCKS!? Now we're talking.",
    "Lemme punch those steel blocks... OW!!!",
    'Fun Fact: the H in "Walker H" stands for "Helmet"',
    "Fun Fact: FlukeDude Ltd is still the legal name for Fluke Games",
    "Fun Fact: Mini Spikes did not exist until the Super Level Pack was released.",
    "Fun Fact: Speed changes can teleport you forwards given enough velocity.",
    "Fun Fact: the property for making the player stick to platforms is reset when editor spawning.",
    "Fun Fact: Player Stacks despawn after around 10 vertical blocks",
    "Fun Fact: 2x Falling Platforms are unreliable",
    "Fun Fact: This game is mobile friendly",
    "Fun Fact: I originally wanted to remake the game. Looks like I have a better way now.",
    "Fun Fact: I am re-making every world level.",
    "Switch SPIKES?! Great, that's it!",
    "The punch powerup removes 2.5 blocks in front of you and 1 1/3 blocks above.",
    "Check out Geometry Dash!",
    "Check out Final Dash!",
    "Check out TIG Infinite!",
    "Check out Userlevels.com!",
    "Player Stacks might despawn. Use with caution.",
    "World 3 is supposed to have triangles in the background. I've added that in!",
    "You can export levels and use them in the original game if you don't use new features.",
    "Always Free!",
    "Always Free!",
    "Always Free!",
    "Puedes cambiar el idioma en el boton de abajo.",
    "Puedes cambiar el idioma en el boton de abajo.",
    "Puedes cambiar el idioma en el boton de abajo.",
    "Puedes cambiar el idioma en el boton de abajo.",
    "Puedes cambiar el idioma en el boton de abajo.",
    "GatoNegro approved!",
    "GatoNegro approved!",
    "Outline/Alfredo Gamer approved!",
    "Outline/Alfredo Gamer approved!",
    "Mikhaelization",
    "Mikhaelization",
    "Falling Saws? Nah, I prefer fireballs.",
    "Critical Hit Missiles? Nah, I prefer minions.",
    'The "Dreamy" background is a shader',
    "The + in the title is there for a reason",
    "Feel free to contribute in the github repo!",
    "Why didn't World 4 have it's own bottom textures?",
    "This is actually based on the android app",
    "Keep the speed in the flag!",
    "Backwards Compatible!",
    "World 5's gonna be CLASSIC (themed)!",
  ],
  currentJoke = JOKES[Math.floor(Math.random() * JOKES.length)];
