// stolen from Snap! ( https://github.com/jmoenig/Snap/blob/master/sw.js )
var version = "1.1.2",
  cacheName = `tig2plus-pwa-${version}`,
  basicFiles = [
    "./index.html",
    "./",

    // program
    "game.js",
    "renderCanvas.js",
    "jokes.js",
    "714.game.js",

    // translations
    "locale/localize.js",
    "locale/es.js",
    "manifest.json",
    "news.json",
    "sw.js",

    // fonts
    "fonts/akashi.ttf", // unused
    "fonts/font-face.css",
    "fonts/Montserrat-Black.ttf",
    "fonts/Montserrat-BlackItalic.ttf",
    "fonts/Montserrat-ExtraBold.ttf",
    "fonts/Montserrat-Medium.ttf",
    "fonts/Montserrat-MediumItalic.ttf",
    "fonts/Montserrat-SemiBold.ttf",
  ],
  audioFiles = [
    // achievement
    "achievement/achievement-unlocked",
    "achievement/rewards-collect",
    // editor
    "editor/place",
    "editor/erase",
    // global
    "global/button-select",
    "global/button",
    "global/purchase-blocks",
    "global/purchase-item",
    "global/sync",
    // levels
    ...[
      // boss 1
      "boss1/death.mp3",
      // boss 2
      "boss2/bullethell_large",
      "boss2/bullethell_small",
      "boss2/damage",
      "boss2/death",
      "boss2/doublemissile",
      "boss2/gun-appear",
      "boss2/gun-retract",
      "boss2/laser",
      "boss2/machinegun",
      // boss 3
      "boss3/death",
      "boss3/rotate",
      "boss3/shoot.mp3",
      // boss 4
      "boss4/block_explosion.mp3",
      "boss4/claw_attack.mp3",
      "boss4/death.mp3",
      "boss4/fireball.mp3",
      "boss4/footstep1",
      "boss4/footstep2",
      "boss4/footstep3",
      "boss4/laser.mp3",
      "boss4/laugh.mp3",
      "boss4/minion.mp3",
      "boss4/tail_attack.mp3",

      // double jump
      "doubleJump/jump",
      "doubleJump/pickup",
      // enemy
      "enemy/explosion",
      "enemy/shoot",
      "enemy/stomped",
      // gun
      "gun/shoot",
      "gun/pickup",
      // jetpack
      "jetpack/finish",
      "jetpack/loop",
      "jetpack/pickup",
      // punch
      "punch/pickup",
      "punch/use",
      // skateboard
      "skateboard/score/1",
      "skateboard/score/2",
      "skateboard/score/3",
      "skateboard/score/4",
      "skateboard/score/5",
      "skateboard/score/6",
      "skateboard/score/7",
      "skateboard/score/8",
      "skateboard/score/9",
      "skateboard/score/10",
      "skateboard/score/add",
      "skateboard/grind",
      "skateboard/move",
      "skateboard/ollie",

      // speedChange
      "speedchange/down1",
      "speedchange/down2",
      "speedchange/down3",
      "speedchange/down4",
      "speedchange/down5",
      "speedchange/up1",
      "speedchange/up2",
      "speedchange/up3",
      "speedchange/up4",
      "speedchange/up5",
      // stack
      "stack/1",
      "stack/2",
      "stack/3",
      "stack/4",
      "stack/5",
      "stack/6",
      "stack/7",
    ].map((file) => "levels/" + file),
    "levels/coin-collect",
    "levels/direction-change",
    "levels/explosion1",
    "levels/explosion2",
    "levels/explosion3",
    "levels/flag",
    "levels/jump",
    "levels/level-complete",
    "levels/missile",
    "levels/object-explosion",
    "levels/portal1",
    "levels/portal2",
    "levels/spring",
    "levels/switch-button.mp3",
    // menu
    "menu/accept",
    "menu/error",
    "menu/party-invite",
    "menu/send",
    // online
    "online/countdown-123",
    "online/countdown-go",
    "online/countdown-start",
    "online/game-over",
    "online/round-finish",
    "online/timer-tick",
    "online/win",
    "online/xp",
  ],
  getWorld1Files = (e) => [
    `images/themes/${e}/background/Blur02.png`,
    `images/themes/${e}/background/Fence03.png`,
    `images/themes/${e}/background/RectangleBG02.png`,
    `images/themes/${e}/background/Shape02.png`,
    `images/themes/${e}/background/Star03.png`,
    `images/themes/${e}/background/Dust.png`,
    `images/themes/${e}/background/Fence04.png`,
    `images/themes/${e}/background/RectangleBG03.png`,
    `images/themes/${e}/background/Shape03.png`,
    `images/themes/${e}/background/Fence01.png`,
    `images/themes/${e}/background/Flara01.png`,
    `images/themes/${e}/background/RectangleBG04.png`,
    `images/themes/${e}/background/Star01.png`,
    `images/themes/${e}/background/Blur01.png`,
    `images/themes/${e}/background/Fence02.png`,
    `images/themes/${e}/background/RectangleBG01.png`,
    `images/themes/${e}/background/Shape01.png`,
    `images/themes/${e}/background/Star02.png`,
    `images/themes/${e}/background/Triangle01.png`,
    `images/themes/${e}/background/Triangle02.png`,
    `images/themes/${e}/background/Triangle03.png`,
    `images/themes/${e}/background/Triangle04.png`,
    `images/themes/${e}/background/Triangle05.png`,
    `images/themes/${e}/background/Triangle06.png`,
    `images/themes/${e}/background/Triangle07.png`,
    `images/themes/${e}/background/Rectangle06.png`,
    `images/themes/${e}/background/RectangleLong.png`,
  ],
  imageFiles = [
    // editor
    "images/editor/delete.png",
    "images/editor/pointer.png",
    "images/editor/eraser.png",
    "images/editor/add.png",
    "images/editor/select.png",
    "images/editor/duplicate.png",
    "images/editor/undo.png",
    "images/editor/theme.png",
    "images/editor/editorOnly/direction-change.png",
    "images/editor/editorOnly/double-jump.png",
    "images/editor/editorOnly/spring.png",
    "images/editor/editorOnly/speed-change.png",

    "images/editor/editorOnly/block-switch-button.png",
    "images/editor/editorOnly/size-button.png",
    "images/editor/objects/miniblock.png",
    "images/editor/objects/block.png",
    "images/editor/objects/platform.png",
    "images/editor/objects/saw.png",
    "images/editor/objects/powerup.png",
    "images/editor/objects/spike.png",
    "images/editor/objects/minispike.png",
    "images/editor/objects/flag.png",
    "images/editor/objects/dirchange.png",
    "images/editor/objects/speedchange.png",
    "images/editor/objects/switch.png",
    "images/editor/objects/portal.png",
    "images/editor/objects/enemy.png",
    "images/editor/objects/spring.png",
    "images/editor/objects/switchplatform.png",
    "images/editor/objects/collectible.png",
    "images/themes/world1/flag.png",
    "images/themes/world1/flagEnd.png",
    // achievement
    "images/achievement/rewards/autopilot.png",
    "images/achievement/rewards/missiles.png",
    "images/achievement/rewards/slowmo.png",
    "images/achievement/rewards/blocks.png",
    "images/achievement/rewards/bonus.png",
    "images/achievement/rewards/editor.png",
    "images/achievement/rewards/theme.png",
    "images/achievement/rewards-hidden.png",
    "images/achievement/buy-pass-marks.png",
    "images/achievement/skater-screenshot.png",
    // level
    "images/level/attempt.png",
    "images/level/arrow-up.png",
    "images/level/arrow-down-stroke.png",
    // online
    "images/online/name-arrow.png",
    "images/online/highlight-player.png",
    "images/online/eye-icon.png",
    // super level pack
    "images/superLevelPack/Default.png",
    "images/superLevelPack/Aura.png",
    "images/superLevelPack/Cool Friends.png",
    "images/superLevelPack/Nacreous Snowmelt.png",
    "images/superLevelPack/For You.png",
    // main menu
    "images/mainMenu/appleid_button.png",
    "images/mainMenu/googlesignin_button.png",
    "images/mainMenu/googlesignin_button_pressed.png",
    "images/mainMenu/rhythm-button-lines.png",
    "images/mainMenu/levelSelect/difficultyIcons/background.png",
    "images/mainMenu/levelSelect/difficultyIcons/1.png",
    "images/mainMenu/levelSelect/difficultyIcons/2.png",
    "images/mainMenu/levelSelect/difficultyIcons/3.png",
    "images/mainMenu/levelSelect/difficultyIcons/4.png",
    "images/mainMenu/levelSelect/difficultyIcons/5.png",
    "images/mainMenu/levelSelect/difficultyIcons/6.png",
    "images/mainMenu/levelSelect/difficultyIcons/7.png",
    "images/mainMenu/levelSelect/difficultyIcons/8.png",
    "images/mainMenu/levelSelect/difficultyIcons/9.png",
    "images/mainMenu/levelSelect/difficultyIcons/10.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/1.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/2.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/3.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/4.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/5.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/6.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/7.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/8.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/9.png",
    "images/mainMenu/levelSelect/difficultyIconsModal/10.png",
    "images/mainMenu/levelSelect/bpm/1.png",
    "images/mainMenu/levelSelect/bpm/2.png",
    "images/mainMenu/levelSelect/bpm/3.png",
    "images/mainMenu/levelSelect/bpm/4.png",
    "images/mainMenu/levelSelect/checkpointsIcon.png",
    "images/mainMenu/levelSelect/checkpointsIconComplete.png",
    "images/mainMenu/levelSelect/noCheckpointsIcon.png",
    "images/mainMenu/levelSelect/noCheckpointsIconComplete.png",
    "images/mainMenu/levelSelect/Level_Locked.png",
    "images/mainMenu/lockIcon.png",
    "images/mainMenu/levelSelect/Star01.png",
    "images/mainMenu/levelSelect/Star02.png",
    "images/mainMenu/flukegames.png",
    "images/mainMenu/logo.png",
    "images/mainMenu/worldSelect/1.png",
    "images/mainMenu/worldSelect/2.png",
    "images/mainMenu/worldSelect/3.png",
    "images/mainMenu/worldSelect/4.png",

    // player
    "images/player/pixel-explosion.png",
    "images/player/glow.png",
    "images/themes/blank/block.png", // players skins are in the "skins" array

    // themes :)

    ...getWorld1Files("world1"),
    ...getWorld1Files("world1Boss"),

    // pixel images
    "images/themes/punch/ground.png",
    "images/themes/punch/idle.png",
    "images/themes/punch/punch.png",

    "images/themes/world2/background/BG_01.png",
    "images/themes/world2/background/BG_02.png",
    "images/themes/world2/background/BG_03.png",
    "images/themes/world2/background/BG_04.png",
    "images/themes/world2/background/BG_05.png",
    "images/themes/world2Red/BG_01.png",
    "images/themes/world2Red/BG_02.png",
    "images/themes/world2Red/BG_03.png",
    "images/themes/world2Red/BG_04.png",
    "images/themes/world2Red/BG_05.png",
    "images/themes/punch/background/BG_01.png",
    "images/themes/punch/background/BG_02.png",
    "images/themes/punch/background/BG_03.png",
    "images/themes/punch/background/BG_04.png",
    "images/themes/punch/background/BG_05.png",
    "images/themes/punch/background/Building_01.png",
    "images/themes/punch/background/cloud_01.png",
    "images/themes/punch/background/cloud_02.png",
    "images/themes/punch/background/cloud_03.png",
    "images/themes/punch/background/cloud_04.png",
    "images/themes/punch/background/ground.png",
    "images/themes/punch/background/moon.png",
    "images/themes/punch/background/water.png",

    "images/themes/world2/enemy-walker-helmet.png",
    "images/themes/world2/enemy-walker.png",
    "images/themes/world2/enemy-walker-stomped.png",
    "images/themes/world2/enemy-explosion.png",

    "images/themes/classic/background/fade.png",
    "images/themes/red/background/background.png",
    "images/themes/red/background/background-red-dots.png",
    "images/themes/red/background/background-red-flame1.png",
    "images/themes/red/background/background-red-flame2.png",
    `images/themes/world3/background/pink-triangle.png`,
    `images/themes/world3/background/red-triangle.png`,
    "images/themes/world3/background/stars-moving.png",
    "images/themes/world3/background/stars-static.png",
    "images/themes/world3/background/cloud.png",
    "images/themes/synthwave/background.png",
    "images/themes/synthwave/mountains.png",

    `images/themes/world4/background/background.png`,
    `images/themes/world4/background/castle.png`,
    `images/themes/world4/background/cloud1.png`,
    `images/themes/world4/background/cloud2.png`,
    `images/themes/world4/background/front-mountain1.png`,
    `images/themes/world4/background/front-mountain2.png`,
    `images/themes/world4/red/background.png`,
    `images/themes/world4/red/castle.png`,
    `images/themes/world4/red/cloud1.png`,
    `images/themes/world4/red/cloud2.png`,
    `images/themes/world4/red/front-mountain1.png`,
    `images/themes/world4/red/front-mountain2.png`,
    `images/themes/world4/boss/background.png`,
    `images/themes/world4/boss/castle.png`,
    `images/themes/world4/boss/cloud1.png`,
    `images/themes/world4/boss/cloud2.png`,
    `images/themes/world4/boss/front-mountain1.png`,
    `images/themes/world4/boss/front-mountain2.png`,
    "images/themes/skater/background/cloud1.png",
    "images/themes/skater/background/cloud2.png",
    "images/themes/skater/background/distant-buildings.png",
    "images/themes/skater/background/distant-buildings2.png",
    "images/themes/skater/background/ground-buildings.png",
    "images/themes/skater/background/hedges.png",
    "images/themes/skater/background/sky-buildings.png",
    "images/themes/skater/background/sky.png",
    "images/themes/speed/moon.png",
    "images/themes/speed/red_moon.png",
    "images/themes/speed/plan1.png",
    "images/themes/speed/ash.png",
    "images/themes/world1/red.png",
    "images/themes/world1/blue.png",
    "images/themes/world1/red-outline.png",
    "images/themes/world1/blue-outline.png",
    "images/themes/world2/block-explosion.png",
    "images/themes/world2/spike-explosion.png",
    "images/themes/world2/gun/bullet.png",
    "images/themes/world2/gun/bullet-enemy.png",
    "images/themes/world2/gun/ground.png",
    "images/themes/world2/gun/idle.png",
    "images/themes/world2/gun/shooting.png",
    "images/themes/world2/jetpack/back-launch.png",
    "images/themes/world2/jetpack/back-on.png",
    "images/themes/world2/jetpack/back-out.png",
    "images/themes/world2/jetpack/back.png",
    "images/themes/world2/jetpack/front-out.png",
    "images/themes/world2/jetpack/front.png",
    "images/themes/world2/jetpack/gauge.png",
    "images/themes/world2/jetpack/ground.png",
    "images/themes/world2/enemy-shooter.png",
    "images/themes/world2/enemy-shooting.png",
    "images/themes/world3/switch-button.png",
    "images/themes/skater/rail.png",
    "images/themes/skater/skateboard.png",
    "images/themes/world3/switch-platform.png",
    "images/themes/world4/portal-green.png",
    "images/themes/world4/portal-yellow.png",
    "images/themes/world4/portal-red.png",
    "images/themes/world4/portal-blue.png",
    "images/themes/synthwave/collectible.png",
    "images/themes/synthwave/collectible-pickup.png",
    "images/themes/arrows/arrow.png",
    "images/themes/arrows/arrow-outline.png",
    "images/themes/arrows/arrow-outline-selected.png",
    "images/themes/world2/flag/end.png",
    "images/themes/world2/flag/idle.png",
    "images/themes/world2/flag/passed.png",
    "images/themes/world2/flag/confetti.png",
    "images/themes/world2/direction-change.png",
    "images/themes/world2/direction-change-hit.png",

    "images/themes/world3/bottom/laser-line.png",
    "images/themes/world3/bottom/block.png",
    `images/themes/classic/bottom/block.png`,

    `images/themes/world1/bottom/block-small-spike.png`,
    `images/themes/world1/bottom/block-spike-corner.png`,
    `images/themes/world1/bottom/block-spike.png`,
    `images/themes/world1/bottom/block.png`,
    `images/themes/world1Boss/bottom/block.png`,
    `images/themes/skater/bottom/block.png`,

    `images/themes/world1/bottom/double-tall-block-spike.png`,
    `images/themes/world1/bottom/tall-block-spike.png`,
    `images/themes/world2/bottom/block-small-spike.png`,
    `images/themes/world2/bottom/block-spike-corner.png`,
    `images/themes/world2/bottom/block-spike.png`,
    `images/themes/world2/bottom/block.png`,
    `images/themes/world2/bottom/double-tall-block-spike.png`,
    `images/themes/world2/bottom/tall-block-spike.png`,
    `images/themes/world4/bottom/block-small-spike.png`,
    `images/themes/world4/bottom/block-spike-corner.png`,
    `images/themes/world4/bottom/block-spike.png`,
    `images/themes/world4/bottom/block.png`,
    `images/themes/world4/bottom/double-tall-block-spike.png`,
    `images/themes/world4/bottom/tall-block-spike.png`,

    // theme files:
    `images/themes/world1/block.png`,
    `images/themes/world1/block-light.png`,
    `images/themes/world1/spike.png`,
    `images/themes/world1/boss.png`,
    `images/themes/world1/steel.png`,
    `images/themes/world1/platform.png`,
    `images/themes/world1/platform-rail.png`,
    `images/themes/world1/saw.png`,
    `images/themes/world1/saw-rail.png`,

    `images/themes/world2/block.png`,
    `images/themes/world2/block-light.png`,
    `images/themes/world2/spike.png`,
    `images/themes/world2/boss.png`,
    `images/themes/world2/steel.png`,
    `images/themes/world2/platform.png`,
    `images/themes/world2/platform-rail.png`,
    `images/themes/world2/saw.png`,
    `images/themes/world2/saw-rail.png`,

    `images/themes/world3/block.png`,
    `images/themes/world3/block-light.png`,
    `images/themes/world3/spike.png`,
    `images/themes/world3/boss.png`,

    `images/themes/world4/block.png`,
    `images/themes/world4/block-light.png`,
    `images/themes/world4/spike.png`,
    `images/themes/world4/boss.png`,
  ],
  skins = [
    "alien",
    "arrows",
    "blank",
    "boss1",
    "boss2",
    "boss3",
    "boss4",
    "bull",
    "burger",
    "calavera",
    "chicken",
    "classic",
    "default",
    "dev",
    "dino",
    "dog",
    "dreamy",
    "fighter",
    "glow",
    "greenbot",
    "knight",
    "layla",
    "machine",
    "monkey",
    "mrcool",
    "mummy",
    "mushroom",
    "parrot",
    "pixel",
    "pixelcheese",
    "pixelcrown",
    "pixelrobot",
    "pixelskull",
    "pumpkin",
    "samurai",
    "skater",
    "space",
    "spaceship",
    "tester",
    "world1",
    "world4",
    "worm",
    "yak",
  ],
  songs = [
    "3b-coincidence.mp3",
    "aaro-indestructable.mp3",
    "adhesive-wombat-8-bit-adventure.mp3",
    "aika-blythe.mp3",
    "amidst-awake.mp3",
    "avenza-solace.mp3",
    "boomkitty-rum-and-bass.mp3",
    "bossfight-pirate-manners.mp3",
    "camellia-nacreous-snowmelt.mp3",
    "chroma-dark-sheep.mp3",
    "colbreakz-for-you.mp3",
    "creo-aura.mp3",
    "cubed-red-shift.mp3",
    "dex-arson-machina.mp3",
    "dj-nate-final-theory.mp3",
    "dj-nate-theory-of-everything-3.mp3",
    "doctor-vox-frontier.mp3",
    "env-heaven.mp3",
    "evilwave-mutant.mp3",
    "exilelord-mechanical-machine.mp3",
    "far-out-overdrive.mp3",
    "geoxor-hellscape.mp3",
    "geoxor-silverdust.mp3",
    "geoxor-stardust.mp3",
    "geoxor-true-colors.mp3",
    "geoxor-virtual.mp3",
    "getsix-sky-fracture.mp3",
    "ghost-n-ghost-lighthouse.mp3",
    "inova-8-bit-shuffle.mp3",
    "inova-octane.mp3",
    "kid2will-fire-aura.mp3",
    "lchvasse-solar-abyss.mp3",
    "mdk-critical-hit.mp3",
    "mdk-super-ultra.mp3",
    "meganeko-breathe.mp3",
    "meganeko-daydreamer.mp3",
    "miami-nights-1984-accelerated.mp3",

    "nitro-fun-dragonfly.mp3",
    "panda-eyes-think-different.mp3",
    "paragonx9-chaoz-fantasy.mp3",
    "silva-hound-cool-friends.mp3",
    "the-brig-polymorph.mp3",
    "tobycreed-phazd.mp3",
    "valesco-cloud-9.mp3",
    "waterflame-clutterfunk.mp3",
    "waterflame-race-around-the-world.mp3",
    "xe-cysmix-oriental-swing.mp3",
  ],
  levels = [],
  spineFiles = [];

var filesToCache = [
  ...basicFiles,
  ...audioFiles.map(
    (file) => "audio/" + file + (file.endsWith(".mp3") ? "" : ".wav"),
  ),
  ...imageFiles,
  ...skins.map((name) => "images/player/skins/" + name + ".png"),
  ...skins.map((name) => "images/player/skins/dark/" + name + ".png"),
  ...levels,
  ...spineFiles,
  "audio/tracks/monstaz-popcorn-funk-credits.mp3",
  "audio/tracks/monstaz-popcorn-funk.mp3",
  "audio/tracks/rustic-runes.mp3",
  ...songs.map((name) => `audio/tracks/${name}`),
  ...songs.map((name) => `audio/snippets/${name}`),
];

console.log("service worker executed", version);
/* Start the service worker and cache all of the app's content */
self.addEventListener("install", function (e) {
  e.waitUntil(
    caches.open(cacheName).then(function (cache) {
      return cache.addAll(filesToCache);
    }),
  );
});

self.addEventListener("activate", (evt) => {
  self.skipWaiting();
  evt.waitUntil(
    caches.keys().then((keyList) => {
      return Promise.all(
        keyList.map((key) => {
          if (key !== cacheName) {
            return caches.delete(key);
          }
        }),
      );
    }),
  );
  self.clients.claim();
});

/* Serve cached content when offline */
self.addEventListener("fetch", function (event) {
  event.respondWith(
    fetch(event.request).catch(function (e) {
      return caches.open(cacheName).then(function (cache) {
        return cache
          .match(event.request, { ignoreSearch: true })
          .then((response) => response);
      });
    }),
  );
});
